export const SOLUTIONS = [
  {
    icon: "👥",
    title: "HRMS",
    subtitle: "Human Resource Management System",
    desc: "A comprehensive HR platform covering the complete employee lifecycle — onboarding, payroll automation, leave management, performance reviews, and statutory compliance. Built to scale with your team.",
    tags: ["Payroll", "Leave Mgmt", "Compliance", "Reports"],
    color: "linear-gradient(135deg,#dbeafe,#eff6ff)",
  },
  {
    icon: "⏱️",
    title: "Web-Based Attendance",
    subtitle: "Smart Attendance Tracking",
    desc: "Browser-based, real-time attendance tracking with biometric integration, geolocation check-in, shift scheduling, and overtime calculation. No app install needed — works on any device.",
    tags: ["Biometric Sync", "Geo Check-in", "Shift Mgmt", "OT Calc"],
    color: "linear-gradient(135deg,#d1fae5,#ecfdf5)",
  },
  {
    icon: "🏢",
    title: "Headcount Management",
    subtitle: "Workforce Strength Analytics",
    desc: "Real-time workforce visibility across all departments, sites, and shifts. Monitor occupancy, track headcount against sanctioned strength, and generate instant analytical reports.",
    tags: ["Multi-site", "Occupancy", "Analytics", "Alerts"],
    color: "linear-gradient(135deg,#fef3c7,#fffbeb)",
  },
  {
    icon: "🪪",
    title: "Visitor Management System",
    subtitle: "Smart Front-Desk Automation",
    desc: "Digital visitor registration with QR-code badges, instant host notification via SMS/email, pre-approval workflows, blacklist management, and full visitor history logs.",
    tags: ["QR Badges", "Host Notify", "Pre-Approval", "Audit Log"],
    color: "linear-gradient(135deg,#fce7f3,#fdf4ff)",
  },
  {
    icon: "💡",
    title: "Custom Business Software",
    subtitle: "Purpose-Built Applications",
    desc: "End-to-end custom development tailored precisely to your workflows — ERP modules, inventory, CRM, billing systems, and more. We build what no off-the-shelf product can.",
    tags: ["ERP", "CRM", "Billing", "Inventory"],
    color: "linear-gradient(135deg,#ede9fe,#f5f3ff)",
  },
  {
    icon: "🔗",
    title: "Hardware + Software Integration",
    subtitle: "Unified Ecosystem by Shee Nithya",
    desc: "Complete hardware procurement, installation, and deep software integration by our sister company Shee Nithya Enterprises. Biometric devices, CCTV, access control, networking — all in one solution.",
    tags: ["Biometric", "CCTV", "Access Ctrl", "Networking"],
    color: "linear-gradient(135deg,#e0f2fe,#f0fdfb)",
  },
];